import React, { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, FileDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useSubscription } from '@/lib/subscriptionContext';
import PaywallModal from '@/components/PaywallModal';
import CalculatorResultsTable from './CalculatorResultsTable';

export default function CalculatorWrapper({ title, icon: Icon, children, onCalculate, calcType }) {
  const sub = useSubscription();
  const [results, setResults] = useState(null);
  const [showPaywall, setShowPaywall] = useState(false);
  const printRef = useRef(null);

  const handleCalculate = () => {
    if (!sub.canCalculate) {
      setShowPaywall(true);
      return;
    }
    const calcResults = onCalculate();
    if (calcResults) setResults(calcResults);
  };

  const handleExportPDF = () => {
    if (!sub.canCalculate) {
      setShowPaywall(true);
      return;
    }
    if (!results) return;

    const rows = results.map(r =>
      `<tr><td>${r.material}</td><td style="text-align:right;font-weight:600">${r.quantity}</td><td>${r.unit}</td><td style="color:#666">${r.notes || ''}</td></tr>`
    ).join('');

    const html = `
      <html><head><title>${title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 32px; color: #111; }
        h1 { font-size: 22px; margin-bottom: 4px; }
        p.sub { color: #666; font-size: 13px; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th { background: #1e2d4d; color: white; padding: 8px 12px; text-align: left; }
        th:nth-child(2) { text-align: right; }
        td { padding: 7px 12px; border-bottom: 1px solid #eee; }
        tr:nth-child(even) td { background: #f8f9fb; }
        .footer { margin-top: 28px; font-size: 11px; color: #999; }
      </style></head>
      <body>
        <h1>${title}</h1>
        <p class="sub">Generated by Buildings Buddy &mdash; ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        <table>
          <thead><tr><th>Material</th><th>Qty</th><th>Unit</th><th>Notes</th></tr></thead>
          <tbody>${rows}</tbody>
        </table>
        <div class="footer">All quantities include standard wastage allowances. Always verify with your supplier before ordering.</div>
      </body></html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
    win.close();
  };

  return (
    <div>
      <Link to="/calculators" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-6 gap-1">
        <ArrowLeft className="w-4 h-4" /> Back to Calculators
      </Link>

      <Card>
        <CardHeader className="border-b border-border">
          <CardTitle className="flex items-center gap-3 font-heading">
            {Icon && <Icon className="w-6 h-6 text-accent" />}
            {title}
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6 space-y-6">
          {children}
          <div className="flex flex-wrap gap-3">
            <Button
              onClick={handleCalculate}
              size="lg"
              className="bg-accent text-accent-foreground hover:bg-accent/90 font-semibold"
            >
              Calculate Materials
            </Button>
            {results && (
              <Button
                onClick={handleExportPDF}
                size="lg"
                variant="outline"
                className="gap-2"
              >
                <FileDown className="w-4 h-4" /> Export PDF
              </Button>
            )}
          </div>
        </CardContent>
      </Card>

      <div ref={printRef}>
        <CalculatorResultsTable results={results} />
      </div>
      <PaywallModal open={showPaywall} onClose={() => setShowPaywall(false)} />
    </div>
  );
}